### ISSUE TITLE
Remaining (non CSS) issues to resolve on slides

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/Education#180]
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by hsoyka** [comment]
Question/Comment: it's unclear from the cover page text that users can also use/access/view additional notes when using the markdown slides in presentation mode. Should/Can we add a third link to the cover page for all modules that links directly to the slide view that includes/makes visible the additional notes text?

**Comment by hsoyka** [comment]
To clarify my previous comment-- the presentation functionality exists/works already, but needs to be more visible both on the cover page and described more clearly in the Readme.

**Comment by amandawhitmire** [comment]
Time to close this issue?

**Comment by aebudden** [comment]
Yes!! Hurrah!
