### ISSUE TITLE
Suggested edits to the DMSH Home page

### ISSUE THREAD

**Issue by dbloom** [DataONEorg/Education#298]
Because Data Management Skillbuilding Hub soooo rolls off the tongue.

Main Page (https://dataoneorg.github.io/Education/)

1st sentence: "The Data Management Skillbuilding Hub contains education resources for better data" DELETE of "education" - it's already implied.

3rd sentence: "..., and a supporting hands-on exercise." DELETE "supporting", it's passive and unnecessary.

4th sentence: "The Data Management Skillbuilding Hub is intended to be flexible and updated by a range of users and audiences, and also to build interest in shared maintenance and sustainability." CHANGE to "The resources presented on the Data Management Skillbuilding Hub can be updated by its users to promote a current, well-maintained, and sustainable educational tool." or something like that.

5th sentence: is fabulous. Really.

**Comment by aebudden** [comment]
All changes made.
