### ISSUE TITLE
Suggested edits to DMSN Contribute page

### ISSUE THREAD

**Issue by dbloom** [DataONEorg/Education#299]
CONTRIBUTE (https://dataoneorg.github.io/Education/CONTRIBUTING)

To address passive voice and an escaping period, CHANGE Intro Statement to:

"This document details our recommended processes and tool to update current content, suggest changes to content, and fork content for your own use, as well as an introduction to how the content is organized.

Thank you for your interest in contributing to these educational materials. This repository was developed by the DataONE Community Engagement and Outreach Working Group and continues to be maintained by members of this team."

In general, I strongly recommend ridding ourselves of the "ings" and extra descriptors to make this page stronger.

For example, the sentence "Forking and editing content through GitHub, rather than downloading and privately editing, enables others to use your edited content and track how these materials are being used." could/should become, "Fork and edit content through GitHub, rather than editing privately, enables others to use your edited content and to track how these materials are used."

We won't get 'em all, but we can sure make it stronger. This is true of all pages, not just CONTRIBUTE.

**Comment by aebudden** [comment]
Suggestions above incorporated. Another review for voice consistency would be valuable.

**Comment by jjmeyeruw** [comment]
It looks pretty good to me - nicely done. Not critical, but the only sentences that I would recommend changes to is below - and it is just re-ordering the two sentences:
"Thank you for your interest in contributing to these educational materials. This repository was developed by the DataONE Community Engagement and Outreach Working Group and continues to be maintained by members of this team."
-to-
"This repository was developed by the DataONE Community Engagement and Outreach Working Group and continues to be maintained by members of this team. Thank you for your interest in contributing to these educational materials."

**Comment by aebudden** [comment]
Suggestion incorporated. Leaving the issue open for more eyes.
