### ISSUE TITLE
Suggested edits to DMSH FAQ page

### ISSUE THREAD

**Issue by dbloom** [DataONEorg/Education#300]
Question 1:

"You will find a series of resources that help users learn to better manage their data; each is focused on one stage of the data lifecycle. Each resource is comprised of supporting materials, such a set of slides with presenter notes, a one-page explanatory sheet, and a hands-on exercise. These materials are meant to be flexible and adaptable for use in a range of contexts. For example, they can be used for personal education, in classroom settings, by librarians teaching data management workshops, and more."

CHANGE to: "You will find a series of resource to help users to better manage their data. Each resource is focused on one or more stages of the life cycle [enter https://www.dataone.org/data-life-cycle] and is comprised of educational materials, such as slides with presenter notes, explanation sheets, and hands-on exercises. These materials are flexible and can be adapted for use in a range of contexts, including personal education, classroom settings, and data management workshops."

Question 5:
"Yes. It is okay for you add new content, or to make changes to existing content and redistribute in ways that suit your needs, such as PowerPoint. For more information visit our Contribute page. We ask that you provide appropriate citation and attribution to DataONE."

CHANGE to: "Yes. You can add new content or make change to existing content in the ways that suit your needs. For more information, visit our Contribute page. If you make changes or additions please provide the appropriate citation and attribution to DataONE. For more information visit our Contribute page."

There are bunches of stylistic changes I could suggest, but I'll leave it at these big ones for now.

**Comment by aebudden** [comment]
All changes implemented
