### ISSUE TITLE
Suggested edit for Header Menu

### ISSUE THREAD

**Issue by dbloom** [DataONEorg/Education#301]
In the header menu containing Home, Contribute, FAQ and GitHub, do we want to/need to place the little arrow icon to let folks know that a new browser page will open in a "technically" different web site?

**Comment by aebudden** [comment]
Only the GitHub link (and DataONE logo) link out to a new site. Do you suggest we just have the arrow for GitHub?

**Comment by aebudden** [comment]
Making an executive decision to close this. I don't think an icon is needed since the negatives (disruption of the header bar, meaning not immediately apparent) might outweigh the benefits. We can reopen if others feel strongly.
