### ISSUE TITLE
Hands-on Exercise links

### ISSUE THREAD

**Issue by dbloom** [DataONEorg/Education#302]
Everywhere in our DMSH we refer to "hands-on" exercises, yet when one of the tiles is clicked, the links to download the documents are all "hands on". Hyphens would be good in these hyperlinks.

**Comment by aebudden** [comment]
@meg3mach Can you go through an add hyphens to the individual content pages?

**Comment by meg3mach** [comment]
Hyphen added, luckily this was on a single page that feeds to all the other pages. Easy-peezy.
