### ISSUE TITLE
Broken download links

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/Education#303]
PPT download, hands-on and one page links broken on all content pages. 

PPT download links to https://www.dataone.org/sites/all/documents/education-modules/pptx/ vs an individual file for download. Error indicates that file is forbidden (though it might be bc it doesn't exist)

Hands-on and one-pagers both link back to the index page and so go nowhere (e.g. https://dataoneorg.github.io/Education/lessons/03_planning/index.html)

**Comment by meg3mach** [comment]
All these are fixed now!
