### ISSUE TITLE
Standard metadata

### ISSUE THREAD

**Issue by tpoisot** [DataONEorg/Education#41]
For each lesson, can we agree on a couple standard yaml fields? I'm thinking about
- `maintainers`
- `keywords`
- `time` (_i.e._ how long it takes to go through)

This will give a richer landing page

**Comment by aebudden** [comment]
YAML fields have been updated with containers and keywords.  Maintainers and time not added.

**Comment by aebudden** [comment]
@datadavev Can this be closed?
