### ISSUE TITLE
fix pptx downloads

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/Education#97]
The education module PPTX files were on the old DataONE web site, and did not get moved to the new Hugo site. Need to:

1) Add the pptx files to this repo
2) Fix the links to those files in lesson pages

**Comment by mbjones** [comment]
Closed in PR #98 . Done.

@angiegarciaa Education lesson PPTs are now on this site and no longer need access to the old site. There may stull be other types of materials there that need to get moved. Let's open other tickets for those.

**Comment by angiegarciaa** [comment]
Yes, there's a couple things Robyn and I discussed to move. We wanted to wait until we all got into a team meeting to discuss since we would be building new pages onto the website to merge things from the old site. @mbjones Thanks for the update on this issue!
